# Generated by Django 4.1.1 on 2022-09-05 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Worker',
            new_name='Workers',
        ),
    ]
