# Generated by Django 4.1.1 on 2022-09-13 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_workers_description_alter_workers_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workers',
            options={'ordering': ['id'], 'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
    ]
