# Generated by Django 4.1.1 on 2022-09-15 19:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_alter_workers_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='age_top',
            field=models.CharField(default=django.utils.timezone.now, max_length=64, verbose_name='age'),
            preserve_default=False,
        ),
    ]
